/*ZAD 1*/
SELECT COUNT(CLASSES.CLASS) AS BBCOUNT
FROM CLASSES
WHERE CLASSES.TYPE='bb'

/*ZAD 2*/
SELECT CLASSES.CLASS, AVG(CLASSES.NUMGUNS) AS NUMG
FROM CLASSES
WHERE CLASSES.TYPE='bb'
GROUP BY CLASS

/*ZAD 3*/
SELECT AVG(CLASSES.NUMGUNS) AS AVGNUM
FROM CLASSES
WHERE CLASSES.TYPE='bb'

/*ZAD 4*/

/*ZAD 5*/
SELECT SHIPS.CLASS, COUNT(OUTCOMES.RESULT) AS SCOUNT
FROM SHIPS JOIN OUTCOMES ON SHIPS.NAME=OUTCOMES.SHIP
WHERE OUTCOMES.RESULT='sunk'
group by CLASS

/*zad 6*/
SELECT CLASS, COUNT(RESULT) AS No_Sunk 
FROM OUTCOMES 
JOIN SHIPS ON SHIPS.NAME = OUTCOMES.SHIP WHERE RESULT = 'sunk' 
AND CLASS IN (SELECT CLASSES.CLASS 
				FROM CLASSES JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS 
				GROUP BY CLASSES.CLASS 
				HAVING COUNT(CLASSES.CLASS) >= 2) 
GROUP BY CLASS;


/*zad 7*/
SELECT COUNTRY, CAST(AVG(BORE) AS decimal(10,2)) AS AVG_BORE 
FROM CLASSES JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS 
GROUP BY COUNTRY;

