SELECT NAME
FROM SHIPS, CLASSES
WHERE CLASSES.DISPLACEMENT>50000 AND SHIPS.CLASS=CLASSES.CLASS;

SELECT SHIPS.NAME, CLASSES.DISPLACEMENT, CLASSES.NUMGUNS
FROM SHIPS, CLASSES, OUTCOMES
WHERE OUTCOMES.BATTLE= 'Guadalcanal' AND OUTCOMES.SHIP=SHIPS.NAME AND SHIPS.CLASS=CLASSES.CLASS;

SELECT DISTINCT CLASSES1.COUNTRY
FROM CLASSES AS CLASSES1, CLASSES AS CLASSES2
WHERE CLASSES1.TYPE<>CLASSES2.TYPE AND CLASSES1.COUNTRY=CLASSES2.COUNTRY;

SELECT OUTCOMES.SHIP
FROM OUTCOMES, BATTLES
WHERE OUTCOMES.RESULT= 'damaged' AND OUTCOMES.BATTLE=BATTLES.DATE 