SELECT PRODUCT.MAKER, LAPTOP.SPEED
FROM PRODUCT, LAPTOP
WHERE HD>9 AND PRODUCT.MODEL=LAPTOP.MODEL;

SELECT laptop.MODEL, PRICE
FROM PRODUCT, LAPTOP
WHERE PRODUCT.MAKER='B' AND PRODUCT.MODEL=LAPTOP.MODEL
union
SELECT pc.MODEL, PRICE
FROM PRODUCT, pc
WHERE PRODUCT.MAKER='B' AND PRODUCT.MODEL=pc.MODEL
union 
SELECT printer.MODEL, PRICE
FROM PRODUCT, printer
WHERE PRODUCT.MAKER='B' AND PRODUCT.MODEL=printer.MODEL;

SELECT PRODUCT.MAKER
FROM PRODUCT
WHERE TYPE='Laptop' and Type!='PC';
 
 SELECT MAKER FROM PRODUCT WHERE TYPE='Laptop'
 EXCEPT
 SELECT MAKER FROM PRODUCT WHERE TYPE='PC';

 SELECT DISTINCT P1.HD
 FROM PC AS P1, PC AS P2
 WHERE P1.CODE <> P2.CODE AND P1.HD= P2.HD;

 SELECT DISTINCT P1.MODEL, P2.MODEL
 FROM PC AS P1, PC AS P2
 WHERE P1.speed=P2.speed AND P1.ram=P2.ram AND P1.MODEL<P2.MODEL;

 SELECT DISTINCT PRODUCT.MAKER
 FROM PRODUCT, PC AS P1, PC AS P2
 WHERE P1.code<>P2.code AND P1.speed>400 AND P2.speed>400 AND PRODUCT.MODEL=P1.MODEL AND PRODUCT.model=P2.MODEL


