/*ZAD 1*/
SELECT DISTINCT M1.NAME
FROM MOVIESTAR AS M1
WHERE M1.GENDER='F' AND M1.NAME IN (SELECT NAME  FROM MOVIEEXEC WHERE NETWORTH>100000)

/*ZAD 2*/
SELECT DISTINCT M1.NAME
FROM MOVIESTAR AS M1, (SELECT NAME  FROM MOVIEEXEC) M2
WHERE M1.NAME<>M2.NAME

/*ZAD 3*/
SELECT DISTINCT M1.TITLE
FROM MOVIE AS M1, MOVIE AS M2
WHERE M2.TITLE='Star Wars' AND M2.LENGTH<M1.LENGTH

/*ZAD 4*/
SELECT M.TITLE, ME1.NAME 
FROM MOVIEEXEC AS ME1,(SELECT NETWORTH  FROM MOVIEEXEC WHERE NAME= 'Merv Griffin') ME2, MOVIE AS M
WHERE ME1.NETWORTH > ME2.NETWORTH AND PRODUCERC#=ME1.CERT# 

