/*ZAD 1*/
SELECT DISTINCT CLASSES.COUNTRY
FROM CLASSES
WHERE NUMGUNS>= ALL(SELECT NUMGUNS FROM CLASSES)

/*ZAD 2*/
SELECT DISTINCT CLASS
FROM SHIPS
WHERE NAME = ANY(SELECT SHIP
				FROM OUTCOMES
				WHERE RESULT ='SUNK')

/*ZAD 3*/
SELECT SHIPS.NAME, SHIPS.CLASS
FROM SHIPS,(SELECT CLASSES.CLASS
			FROM CLASSES
			WHERE CLASSES.BORE=16) AS C
WHERE SHIPS.CLASS=C.CLASS

/*ZAD 4*/
SELECT OUTCOMES.BATTLE
FROM OUTCOMES, (SELECT SHIPS.NAME
				FROM SHIPS
				WHERE SHIPS.CLASS='Kongo') AS S
WHERE OUTCOMES.SHIP=S.NAME

/*ZAD 5*/
SELECT SHIPS.CLASS, SHIPS.NAME
FROM SHIPS
WHERE CLASS IN(SELECT CLASS
				FROM  CLASSES AS C
				WHERE NUMGUNS>=ALL(SELECT NUMGUNS
									FROM CLASSES
									WHERE BORE=ANY(SELECT BORE
													FROM CLASSES
													WHERE C.BORE=BORE)))